### ISSUE TITLE
add app icon

### ISSUE THREAD

**Issue by rudrankbasant** [ACM-VIT/AlarmIT#3]

**Comment by Kardelio** [comment]
Would you mind if i pick up this ticket? I would like to try and flex my creative icon making skills and this could be a great ticket to do this.
Is that ok if I take this?

**Comment by rudrankbasant** [comment]
Hey @Kardelio, we would love that!

**Comment by Kardelio** [comment]
@rudrankbasant I have addressed this issue in this PR: #7

**Comment by Kardelio** [comment]
@rudrankbasant do you like the icon?

This is the base image for the icon btw:

![base-image-for-icon](https://user-images.githubusercontent.com/10523656/195899452-d7c1483c-81e4-4697-8a7e-cbe74f288edf.png)
