### ISSUE TITLE
add item-view layout for alarm

### ISSUE THREAD

**Issue by rudrankbasant** [ACM-VIT/AlarmIT#5]
The item view is split into two rows:
1) TOP ROW (with a width greater than the bottom row)
          1) Time of the alarm on left.
          2) A toggle button on the right.

2) BOTTOM ROW
        1) Left side has 7 letters - SMTWTFS
        2) Right side has a kebab menu ( triple vertical dots menu option)

**Comment by watermelon3093** [comment]
Hey, can I take up this issue?
